version: "3.7"
  services:
    angular:
      build: ./devops-web
      ports:
        - "8080:80"
    chuck:
      build: ./devops-app
      ports:
        - "3001:3001"
    dogs:
      build: ./devops-db-app
      ports:
        - "3000:3000"
      depends_on: 
        - db
    db:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      restart: always
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: database
        MYSQL_USER: admin
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  volumes:
    mysql_data:
